CREATE TABLE CLIENTES
(
    CODIGO_CLI  NUMBER,
    NOME_CLI    VARCHAR(100) NOT NULL,
    TEL_CLI     NUMBER (11),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO_CLI)
);

CREATE TABLE AUTOMOVEL
(
    renavam varchar(11),
    PLACA   VARCHAR(8) NOT NULL,
    CHASSI  VARCHAR(25) NOT NULL,
    MODELO  VARCHAR(50),
    ANO     NUMBER(4),
    CODIGO_CLI NUMBER,
    CONSTRAINT PK_AUTOMOVEL PRIMARY KEY  (RENAVAM),
    CONSTRAINT FK_AUTOMO0VEL FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTES (CODIGO_CLI)
);

CREATE TABLE RELATO
(
    CODIGO_REL      NUMBER,
    DESCRICAO_REL   VARCHAR(100),
    DATA_REL        DATE,
    RENAVAM         VARCHAR(11),
    CONSTRAINT PK_RELATO PRIMARY KEY (CODIGO_REL),
    CONSTRAINT FK_RELATO FOREIGN KEY (RENAVAM)REFERENCES AUTOMOVEL(RENAVAM)
);

CREATE TABLE ORCAMENTO
(
    CODIGO_ORC      NUMBER,
    MECANICO_ORC    VARCHAR(100) NOT NULL,
    DATA_ORC        DATA,
    VALOR_TOTAL     NUMBER(7, 2),
    RENAVAM         VARCHAR(11),
    CONSTRAINT PK_ORC PRIMARY KEY (CODIGO_ORC),
    CONSTRAINT FK_ORC FOREIGN KEY (RENAVAM) REFERENCES AUTOMOVEL (RENAVAM)
);

CREATE TABLE SERVICOS
(
    CODIGO_SER      NUMBER,
    DESCRICAO_SER   VARCHAR(100),
    VALOR_SER       NUMBER(7,2),
    CONSTRAINT PK_SERVICO PRIMARY KEY (CODIGO_SER)
);

CREATE TABLE ORC_SERV
(
    CODIGO_SER      NUMBER,
    CODIGO_ORC      NUMBER,
    CONSTRAINT FK_ORC_SERV FOREIGN KEY (CODIGO_SER) REFERENCES SERVICOS (CODIGO_SER),
    CONSTRAINT FK_ORC_SERV2 FOREIGN KEY (CODIGO_ORC) REFERENCES ORCAMENTO(CODIGO_ORC)
);

CREATE TABLE PECAS
(
    CODIGO_PEC      NUMBER,
    DESCRICAO_PEC   VARCHAR(100),
    QTDE_PEC        NUMBER,
    VALOR_PEC       NUMBER(7,2),
    CONSTRAINT PK_PECAS PRIMARY KEY (CODIGO_PEC)
)

CREATE TABLE ORC_PECA
(
    CODIGO_PEC NUMBER,
    CPDIGO_ORC NUMBER,
    CONSTRAINT FK_ORC_PEC FOREIGN KEY (CODIGO_PER) REFERENCES SERVICOS (CODIGO_PER),
    CONSTRAINT FK_ORC_PEC2 FOREIGN KEY (CODIGO_ORC) REFERENCES ORCAMENTO(CODIGO_ORC)
);